const countryCurrencyOptions = [
    { label: 'Chile (CLP)', value: 'CLP' },
    { label: 'United States (USD)', value: 'USD' },
    { label: 'Argentina (ARS)', value: 'ARS' },
    { label: 'Brazil (BRL)', value: 'BRL' },
    { label: 'Canada (CAD)', value: 'CAD' },
    { label: 'China (CNY)', value: 'CNY' },
    { label: 'Eurozone (EUR)', value: 'EUR' },
    { label: 'India (INR)', value: 'INR' },
    { label: 'Japan (JPY)', value: 'JPY' },
    { label: 'Mexico (MXN)', value: 'MXN' },
    { label: 'Russia (RUB)', value: 'RUB' },
    { label: 'South Africa (ZAR)', value: 'ZAR' },
    { label: 'Australia (AUD)', value: 'AUD' },
    { label: 'New Zealand (NZD)', value: 'NZD' },
    { label: 'United Kingdom (GBP)', value: 'GBP' },
    { label: 'South Korea (KRW)', value: 'KRW' },
    { label: 'Switzerland (CHF)', value: 'CHF' },
    { label: 'Turkey (TRY)', value: 'TRY' },
    { label: 'Norway (NOK)', value: 'NOK' },
    { label: 'Sweden (SEK)', value: 'SEK' },
    { label: 'Denmark (DKK)', value: 'DKK' },
    { label: 'Poland (PLN)', value: 'PLN' },
    { label: 'Saudi Arabia (SAR)', value: 'SAR' },
    { label: 'Indonesia (IDR)', value: 'IDR' },
    { label: 'Thailand (THB)', value: 'THB' },
    { label: 'Malaysia (MYR)', value: 'MYR' },
    { label: 'Singapore (SGD)', value: 'SGD' },
    { label: 'Hong Kong (HKD)', value: 'HKD' },
    { label: 'Philippines (PHP)', value: 'PHP' },
    { label: 'Israel (ILS)', value: 'ILS' },
  ];
  
  export default countryCurrencyOptions;
  